#! /bin/sh

sxhkd &
xrdb ~/.Xresources &
$HOME/.config/polybar/launch.sh
xwallpaper --zoom Data/Pictures/Wallpapers/nature/starry-night-over-corsica-wallpaper-for-1920x1080-63-986.jpg
synclient TapButton1=1
synclient TapButton2=3
udiskie &
dunst &
picom --experimental-backends &


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
